
network_output_directory: testoutput
overwriteOutput: True
#output_directory: 'W:\statewide\aqua_map3D\am_references\MarsMapMethods\tutorial\example_network_output'
#overwriteOutput: True
basin: 'DelawareBasin'
workspace_major: working_geodb_and_folders_ex
working_geodb_name: working_geodb_example.gdb
working_folder: working_folder_example
do_qc: False
model_extent_polygon: 'E:\3D_spatial_general\3d mapping areas\Delaware_Basin.shp'
unitnames:
  - alvb
  - udb
elevIDs:
  - alv_b_elev
  - ud_b_elev
extent:
  xmin: 485690
  ymin: 3530089
  xmax: 693190
  ymax: 3627589
