input_directory: ./exampledata
output_directory: ./exampleoutput
overwrite_output: True
step1:
  arcpy_workspace: E:\DelawareBasin\DelawareBasin_geodata\workingdata\dbasin_geodata_originals5_deccheck.gdb
  arcpy_snapRaster: E:\DelawareBasin\DelawareBasin_geodata\workingdata\BASEMAP.gdb\z_snapraster
  out_geodb: E:\DelawareBasin\DelawareBasin_geodata\workingdata\QCoutputs_v12.gdb